basePath: /
definitions:
  models.Answer:
    properties:
      answer:
        items:
          $ref: '#/definitions/models.Answer'
        type: array
      id:
        example: 7f484f697ee1283a0ca5a028
        type: string
      likes:
        example: 10
        type: integer
      parent:
        example: 5f484f697ee3881a0ca9a037
        type: string
      text:
        example: How can I remove an item?
        type: string
    type: object
  models.Question:
    properties:
      id:
        example: 5f484f697ee3881a0ca9a037
        type: string
      image:
        example: http://nuorder.com/images/image.jpg
        type: string
      likes:
        example: 30
        type: integer
      text:
        example: How can I remove an item?
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: flavio.costa@ecore.com.br
    name: NuOrder API Support
  description: This is a MVP for Questions and Answers for https://www.nuorder.com/ page
  license:
    name: Apache 2.0
    url: https://www.nuorder.com/licenses/LICENSE-2.0.html
  termsOfService: https://www.nuorder.com/
  title: FAQ API
  version: "1.0"
paths:
  /api/v1/answer:
    get:
      consumes:
      - application/json
      description: Get a list of all questions and answers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Answer'
            type: array
      summary: Get a list to all questions and answers from API
      tags:
      - faq
  /api/v1/answer/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a question and answer
      parameters:
      - description: ObjectId
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'result: success'
      summary: Delete one question and answer item from the API
      tags:
      - faq
    get:
      consumes:
      - application/json
      description: Get a question and answer
      parameters:
      - description: ObjectId
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Answer'
      summary: Get one question and answer item from the API
      tags:
      - faq
    put:
      consumes:
      - application/json
      description: Update a new Question and Answer with the input paylod
      parameters:
      - description: ObjectId
        in: path
        name: id
        required: true
        type: string
      - description: Update
        in: body
        name: faq
        required: true
        schema:
          $ref: '#/definitions/models.Answer'
      produces:
      - application/json
      responses:
        "200":
          description: ObjectIdHex(id), was successful updated!
      summary: Update a new Question and Answer item
      tags:
      - faq
  /api/v1/faq:
    post:
      consumes:
      - application/json
      description: Create a new Question and Answer with the input paylod
      parameters:
      - description: Create
        in: body
        name: faq
        required: true
        schema:
          $ref: '#/definitions/models.Answer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Answer'
      summary: Create a new Question and Answer item
      tags:
      - faq
  /api/v1/question:
    get:
      consumes:
      - application/json
      description: Get a list of all questions and answers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Question'
            type: array
      summary: Get a list to all questions and answers from API
      tags:
      - faq
    post:
      consumes:
      - application/json
      description: Create a new Question and Answer with the input paylod
      parameters:
      - description: Create
        in: body
        name: faq
        required: true
        schema:
          $ref: '#/definitions/models.Question'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Question'
      summary: Create a new Question and Answer item
      tags:
      - faq
  /api/v1/question/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a question and answer
      parameters:
      - description: ObjectId
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'result: success'
      summary: Delete one question and answer item from the API
      tags:
      - faq
    get:
      consumes:
      - application/json
      description: Get a question and answer
      parameters:
      - description: ObjectId
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Question'
      summary: Get one question and answer item from the API
      tags:
      - faq
    put:
      consumes:
      - application/json
      description: Update a new Question and Answer with the input paylod
      parameters:
      - description: ObjectId
        in: path
        name: id
        required: true
        type: string
      - description: Update
        in: body
        name: faq
        required: true
        schema:
          $ref: '#/definitions/models.Question'
      produces:
      - application/json
      responses:
        "200":
          description: ObjectIdHex(id), was successful updated!
      summary: Update a new Question and Answer item
      tags:
      - faq
swagger: "2.0"
