basePath: /
definitions:
  models.Answer:
    properties:
      answer:
        items:
          $ref: '#/definitions/models.Answer'
        type: array
      id:
        example: 7f484f697ee1283a0ca5a028
        type: string
      likes:
        example: 10
        type: integer
      parent:
        example: 5f484f697ee3881a0ca9a037
        type: string
      root:
        example: 5f484f697ee3881a0ca9a037
        type: string
      text:
        example: How can I remove an item?
        type: string
    type: object
  models.AnswerRequest:
    properties:
      id:
        example: 7f484f697ee1283a0ca5a028
        type: string
      likes:
        example: 10
        type: integer
      parent:
        example: 5f484f697ee3881a0ca9a037
        type: string
      root:
        example: 5f484f697ee3881a0ca9a037
        type: string
      text:
        example: How can I remove an item?
        type: string
    type: object
  models.Question:
    properties:
      id:
        example: 5f484f697ee3881a0ca9a037
        type: string
      image:
        example: http://example.com/images/image.jpg
        type: string
      likes:
        example: 30
        type: integer
      text:
        example: How can I remove an item?
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: flavio.costa@ecore.com.br
    name: example API Support
  description: |-
    This is a MVP for Questions and Answers for https://www.example.com/ page.
    Install MongoDB to test this service or use Docker executing Compose up in docker-compose.yml in the project folder check the CLI for reference in https://docs.docker.com/compose/reference/up/
    If executing this service by VS Code, just click on right button on docker-compose.yml and Compose Up
  license:
    name: Apache 2.0
    url: https://www.example.com/licenses/LICENSE-2.0.html
  termsOfService: https://www.example.com/
  title: FAQ RESTful Service API
  version: "1.0"
paths:
  /api/v1/answer:
    post:
      consumes:
      - application/json
      description: |-
        Create a new Answer with the input paylod
        The root is the question ID
        The Parent field is the ID of another question that will be answered
      parameters:
      - description: Create
        in: body
        name: faq
        required: true
        schema:
          $ref: '#/definitions/models.AnswerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Answer'
      summary: Create a new Answer item
      tags:
      - Answer
  /api/v1/answer/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a question and answer
      parameters:
      - description: ObjectId
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'result: success'
      summary: Delete one question and answer item from the API
      tags:
      - Answer
    get:
      consumes:
      - application/json
      description: Get an answer by ID
      parameters:
      - description: ObjectId
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Answer'
      summary: Get one answer item from the API
      tags:
      - Answer
    put:
      consumes:
      - application/json
      description: Update a new Question and Answer with the input paylod
      parameters:
      - description: ObjectId
        in: path
        name: id
        required: true
        type: string
      - description: Update
        in: body
        name: faq
        required: true
        schema:
          $ref: '#/definitions/models.Answer'
      produces:
      - application/json
      responses:
        "200":
          description: ObjectIdHex(id), was successful updated!
      summary: Update a new Question and Answer item
      tags:
      - Answer
  /api/v1/answer/{idquestion}:
    get:
      consumes:
      - application/json
      description: Get a list of all answers from a question
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Answer'
            type: array
      summary: Get all answers from a specific Question
      tags:
      - Answer
  /api/v1/question:
    get:
      consumes:
      - application/json
      description: Get a list of all questions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Question'
            type: array
      summary: Get a list to all questions from the API
      tags:
      - Question
    post:
      consumes:
      - application/json
      description: Create a new Question and Answer with the input paylod
      parameters:
      - description: Create
        in: body
        name: faq
        required: true
        schema:
          $ref: '#/definitions/models.Question'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Question'
      summary: Create a new Question and Answer item
      tags:
      - Question
  /api/v1/question/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a question and all the answers
      parameters:
      - description: ObjectId
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'result: success'
      summary: Delete one question and  all answers items from the API
      tags:
      - Question
    get:
      consumes:
      - application/json
      description: Get a question and answer
      parameters:
      - description: ObjectId
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Question'
      summary: Get one question and answer item from the API
      tags:
      - Question
    put:
      consumes:
      - application/json
      description: Update a new Question and Answer with the input paylod
      parameters:
      - description: ObjectId
        in: path
        name: id
        required: true
        type: string
      - description: Update
        in: body
        name: faq
        required: true
        schema:
          $ref: '#/definitions/models.Question'
      produces:
      - application/json
      responses:
        "200":
          description: ObjectIdHex(id), was successful updated!
      summary: Update a new Question and Answer item
      tags:
      - Question
swagger: "2.0"
